language: node_js
matrix: 
  include: 
    - 
      env: PACKAGE_LOCATION="packages/auth"
      name: "auth pipeline"
    - 
      env: PACKAGE_LOCATION="packages/text-extract"
      name: "services ui pipeline"
node_js: 
  - "10.13.0"
script: 
  - "cd $PACKAGE_LOCATION"
  - "npm test"
  - "npm run-script build"
