name: test

on: 
  push:
    branches:
      - feature/npm-bump 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: feature/npm-bump
    - name: Install Lerna
      run: npm install lerna
    - name: Lerna Bootstrap
      run: node_modules/lerna/cli.js bootstrap
    - name: Bump Version Patch
      run: node_modules/lerna/cli.js version patch
    - name: Push update to Github
      uses: github-actions-x/commit@v2.3
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'feature/npm-bump'
        commit-message: 'bump version : patch'
        name: dennyabrain
        email: denny@tattle.co.in
        
